name: SudoScan Master CI
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      # Push events on master branch
      - master
jobs:
  gradle_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set up git
        run: git config user.email "${{ github.actor }}@users.noreply.github.com" && git config user.name "Github Actions"
      - name: Setting up JAVA
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Running gradle task
        uses: eskatos/gradle-command-action@v1
        env:
          USERNAME: ${{ secrets.USERNAME }}
          TOKEN: ${{ secrets.TOKEN }}
        with:
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          gradle-version: wrapper
          arguments: clean assembleDesktopApp release -Prelease.useAutomaticVersion=true
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sudoscan desktop-app jar
          path: build/*.jar
