name: SudoScan Master CI
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      # Push events on master branch
      - master
jobs:
  gradle_build:
    name: Gradle Build on master
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Seting up Git
        run: git config user.email "${{ github.actor }}@users.noreply.github.com" && git config user.name "Github Actions"

      - name: Setting up JAVA
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Running gradle task
        uses: eskatos/gradle-command-action@v1
        env:
          USERNAME: ${{ secrets.USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          gradle-version: wrapper
          arguments: clean assembleCliApp codeCoverageReport sonarqube release -Prelease.useAutomaticVersion=true

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sudoscan client app jar
          path: build/*.jar

  release:
    name: Create Release Tag
    runs-on: ubuntu-latest
    needs: gradle_build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_latest_tag
        run: |
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "::set-output name=latest_tag::$LATEST_TAG"

      - name: Last Release
        id: last_release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}
          excludes: prerelease,draft

      - name: Download Kaggle models
        id: kaggle_download
        run: |
          mkdir recognizer-model
          wget -O recognizer-model/sudoscan-djl.zip https://bit.ly/3mMOpon
          wget -O recognizer-model/sudoscan-dl4j.h5 https://bit.ly/3Dz2Ent

      - name: Release
        uses: softprops/action-gh-release@v1
        if: steps.get_latest_tag.outputs.latest_tag != steps.last_release.outputs.release
        with:
          repository: ${{ github.repository }}
          tag_name: ${{ steps.get_latest_tag.outputs.latest_tag }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            recognizer-model/sudoscan-djl.zip
            recognizer-model/sudoscan-dl4j.h5
