name: SudoScan Develop CI
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - 'develop'
      - 'feature/**'
      - 'hotfix/**'
      - 'bugfix/**'
      - 'release/**'
      - 'support/**'
jobs:
  gradle_dev_build:
    name: Gradle Dev Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setting up JAVA
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Running gradle task
        uses: eskatos/gradle-command-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JFROG_USER: ${{ secrets.JFROG_USER }}
          JFROG_PASS: ${{ secrets.JFROG_PASS }}
        with:
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          gradle-version: wrapper
          arguments: clean codeCoverageReport sonarqube publishGprPublicationToSudoscanLibsRepository