name: SudoScan Create Release Tag
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*'

jobs:
  release:
    name: Create Release Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: recognizer-model/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true